[config]
filhos_por_100_partos = 100
tempo_prenhez_meses = 6
tempo_amamentando_meses = 3
idade_abate_cabrito = 6
tempo_crescimento_matriz = 6
tempo_vida_matriz = 20
teto_matriz = 2000
init_matrizes = 100
init_cabritos = 500
# init_matrizes_idade = 0
# init_cabritos_idade = 0
rt_meses = 240
